[package]
name = "bulk-wallet-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
dotenv = "0.15.0"
tokio = { version= "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
ethers = "0.17.0"

